name: dx
description: A toolbox for dart/Flutter. It could speed up your development work.
version: 1.0.2
homepage: https://github.com/androidyue/dx

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
